version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: obatis-app
    volumes:
      - ../:/var/www
    restart: unless-stopped
    networks:
      - obatis-net

  nginx:
    image: nginx:alpine
    container_name: obatis-nginx
    ports:
      - "80:80"
    volumes:
      - ../:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - obatis-net

networks:
  obatis-net:
    driver: bridge
